#!/usr/bin/with-contenv bash

# create torrent group
groupadd -g $TGID torrent

# add user to torrent group
gpasswd -a abc torrent

# make folders
mkdir -p \
	/downloads/downloading /watch

# copy config
[[ ! -f /config/settings.json ]] && cp \
	/defaults/settings.json /config/settings.json

# copy blocklist-update script
[[ ! -f /config/blocklist-update.sh ]] && cp \
	/defaults/blocklist-update.sh /config/blocklist-update.sh

# permissions
chown abc:torrent \
	/config/settings.json \
	/config/blocklist-update.sh \
	/downloads/downloading \
	/watch

chown :torrent \
	/downloads

chmod 755 /config/blocklist-update.sh
